
package at.kleinknes.bookservicewebapp;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BookWS", targetNamespace = "http://BookServiceWebApp.kleinknes.at/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BookWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveBook", targetNamespace = "http://BookServiceWebApp.kleinknes.at/", className = "at.kleinknes.bookservicewebapp.SaveBook")
    @ResponseWrapper(localName = "saveBookResponse", targetNamespace = "http://BookServiceWebApp.kleinknes.at/", className = "at.kleinknes.bookservicewebapp.SaveBookResponse")
    public boolean saveBook(
        @WebParam(name = "arg0", targetNamespace = "")
        Book arg0);

    /**
     * 
     * @return
     *     returns java.util.List<at.kleinknes.bookservicewebapp.Book>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllBooks", targetNamespace = "http://BookServiceWebApp.kleinknes.at/", className = "at.kleinknes.bookservicewebapp.GetAllBooks")
    @ResponseWrapper(localName = "getAllBooksResponse", targetNamespace = "http://BookServiceWebApp.kleinknes.at/", className = "at.kleinknes.bookservicewebapp.GetAllBooksResponse")
    public List<Book> getAllBooks();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveBooks", targetNamespace = "http://BookServiceWebApp.kleinknes.at/", className = "at.kleinknes.bookservicewebapp.SaveBooks")
    @ResponseWrapper(localName = "saveBooksResponse", targetNamespace = "http://BookServiceWebApp.kleinknes.at/", className = "at.kleinknes.bookservicewebapp.SaveBooksResponse")
    public boolean saveBooks(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Book> arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<at.kleinknes.bookservicewebapp.Book>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchBooks", targetNamespace = "http://BookServiceWebApp.kleinknes.at/", className = "at.kleinknes.bookservicewebapp.SearchBooks")
    @ResponseWrapper(localName = "searchBooksResponse", targetNamespace = "http://BookServiceWebApp.kleinknes.at/", className = "at.kleinknes.bookservicewebapp.SearchBooksResponse")
    public List<Book> searchBooks(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
